### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by alexbelgium** [SimonGuilbert/Genealogy#1]
Hi, how to run? I've installed python 3.9 and executing the script gives : 
```
>>> C:\Downloads\Genealogy-main\backend\webScraping.py
  File "<stdin>", line 1
    C:\Downloads\Genealogy-main\backend\webScraping.py
                                                     ^
SyntaxError: unexpected character after line continuation character
```
Or is it python 2 ?

Thanks very much :-)

**Comment by SimonGuilbert** [comment]
Hi Alexandre, the program should work with Python 3.9. You have to write two arguments : the name you are interested in, and the number of persons you want to add in the database. For example : 
`C:\Downloads\Genealogy-main\backend\python webScraping.py macron 50`
The number must be equal to 50,100,150,200,... It only works for French names. Then you'll have to wait until the program ends (it can take a while)
Have fun!

**Comment by alexbelgium** [comment]
Thanks I'll test it!
